#ifndef BIOS_MEMORY_TYPE_H
#define BIOS_MEMORY_TYPE_H

#define BIOS_USUABLE_MEMORY 1
#define BIOS_RESERVED_MEMORY 2
#define BIOS_ACPI_RECLAIMABLE_MEMORY 3
#define BIOS_ACPI_NVS_MEMORY 4
#define BIOS_BAD_MEMORY 5

#define BIOS_USUABLE_AREA BIOS_USUABLE_MEMORY

#endif